### PR TITLE
Canadian ZipCodes

### PR DESCRIPTION
**Pull request by robblovell**
Here's a first draft of Canadian postal codes.  It does a 3 character lookup and distances between two codes, but the city lookup isn't working right because of the data set.

#10

### CODE REVIEW

**Comment by davglass** [comment]
I just updated the `.travis.yml` file with the latest versions of Node. If you rebase `master` your PR builds should work again.

**Comment by davglass** [comment]
Does the city lookup work?

**Comment by robblovell** [comment]
No, the city data wasn't in the data set.

**Comment by davglass** [comment]
Published in `zipcodes@3.0.0`

**Pull request merged**
